/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ezTQtwNebi0
 */


export function Abouut() {
  return (
    <main className="flex flex-col items-center justify-center space-y-8 p-4 md:p-8">
      <div className="flex flex-col w-full max-w-2xl p-4 mx-auto space-y-6 bg-white rounded-lg shadow-md dark:bg-gray-800">
        <h1 className="text-3xl font-bold text-center">About Us</h1>
        <p className="text-gray-600 dark:text-gray-400">
          Welcome to our dApp! We are a team of dedicated developers committed to simplifying the immigration process.
          Our dApp is designed to automate the filling of forms during the application for immigration services.
        </p>
        <p className="text-gray-600 dark:text-gray-400">
          Our team, consisting of James, David, and John, has worked tirelessly to ensure that our dApp is
          user-friendly, efficient, and secure. We believe in the power of technology to make complex processes like
          immigration simpler and more accessible to everyone.
        </p>
        <h2 className="text-2xl font-bold text-center">How it Works</h2>
        <p className="text-gray-600 dark:text-gray-400">Our dApp works in three simple steps:</p>
        <ol className="list-decimal list-inside text-gray-600 dark:text-gray-400">
          <li>Choose Service: Select the immigration service you need assistance with.</li>
          <li>
            Fill User Info: Temporarily fill in your user information. Rest assured, this information is deleted from
            the blockchain 30 seconds after use.
          </li>
          <li>Apply: With a simple click, our dApp automates the process, saving you time and effort.</li>
        </ol>
      </div>
    </main>
  )
}
